id = "aoe2-rms"
name = "Aoe2 Random Map Script"
version = "0.0.1"
schema_version = 1
authors = ["Travis Westura <twestura@gmail.com>"]
description = "Syntax highlighting for Age of Empires II random map scripts."

[grammars.aoe2_rms]
repository = "file:///C:/Users/Warren/Desktop/aoe2-rms-extensions/tree-sitter-aoe2-rms"
rev = "1cda528f2b64abd2d25d72039b406c7743afeaed"
