id = "aoe2-rms"
name = "Aoe2 Random Map Script"
version = "0.0.1"
schema_version = 1
authors = ["Travis Westura <twestura@gmail.com>"]
description = "Syntax highlighting for Age of Empires II random map scripts."

[grammars.aoe2_rms]
repository = "https://github.com/twestura/tree-sitter-aoe2-rms"
rev = "c8b7ed43af73f9cc06cd96898846cd4dbfe44ad4"
